### ISSUE TITLE
Add ability to expire cache of downloaded p2 repo (index?)

### ISSUE THREAD

**Issue by CptMauli** [mbarbero/fr.obeo.releng.targetplatform#78] opened 2018-06-15 14:48 UTC
I sometimes assemble p2 repos for dependencies manually. If I want to create a new target platform file, or just browse the repo after I changed it, still the cached version of the last time the repo (index) was downloaded.

I want to have the ability to clear this cache (even if it is in the preferences, that would be enough)

**Comment by col-panic** [comment] 2018-06-15 14:58
That would be great! I currently do always restart Eclipse in such a case ...

**Comment by mbarbero** [comment] 2018-06-15 15:08
IIRC, there is a dot folder created besides your target platform dsl file.
Just delete it, and all the caches will be gone.

**Comment by mbarbero** [comment] 2018-06-15 15:21
comment above is wrong. Sorry.

this one is actually a duplicate of #33. Closing

**Closed by mbarbero** 2018-06-15 15:21 UTC
