### ISSUE TITLE
target file generation aborts without any notice / exception

### ISSUE THREAD

**Issue by wohaug** [mbarbero/fr.obeo.releng.targetplatform#61] opened 2015-10-29 13:59 UTC
Assume I have a TPD file like this with on or more includes:

target "PRODUCT"
environment win32 win32 JavaSE-1.7
with source configurePhase
include "platform:/resource/com.x.y.z/com.x.y.z.releng.targetplatform.tpd"
location "<my location>" {
    com.x.y.z.feature.feature.group lazy
}
 
Issue is: When I generate my target file and the project that contains the included tpd file is closed ("com.x.y.z"), the generation of the target file aborts without any notification or exception.

**Comment by mbarbero** [comment] 2015-10-30 08:44
duplicate of #60

**Closed by mbarbero** 2015-10-30 08:44 UTC
Labels: duplicate
